# FILEPATH: /home/taorepoara/lenra/api/components/stack.yml
$schema: https://raw.githubusercontent.com/lenra-io/ex_component_schema/beta/priv/static/draft-lenra.json
$id: components/stack.yml
title: Stack
description: Element of type Stack
type: object
properties:
    _type:
        description: The identifier of the component
        const: stack
    children:
        description: The children of the Stack.
        type: array
        items:
            $ref: ../lenra-component.yml
    alignment:
        $ref: ../defs/alignment.yml
    fit:
        $ref: ../defs/stackFit.yml
required:
    - type
    - children
additionalProperties: false
