# FILEPATH: /home/taorepoara/lenra/api/components/stack.yml
$schema: https://raw.githubusercontent.com/lenra-io/ex_component_schema/beta/priv/static/draft-lenra.json
$id: components/stack.yml
title: Stack
description: Element of type Stack
allOf:
  - $ref: ./_abstract.yml
  - properties:
      _type:
        const: stack
      children:
        description: The children of the Stack.
        type: array
        items:
            $ref: ../lenra-component.yml
      alignment:
        $ref: ../defs/alignment.yml
      fit:
        $ref: ../defs/stackFit.yml
required:
  - children
additionalProperties: false
