openapi: 3.1.0
info:
  title: Lenra App API
  description: Lenra App API documentation
  license:
    name: MIT
  version: 0.0.0
  contact:
    name: Lenra
    url: https://www.lenra.io/contact.
servers:
- url: 'http://localhost:8080'
  description: Exposed devtool app
paths:
  "/*":
    post:
      summary: App request
      operationId: app-request
      description: Request to a Lenra app
      tags:
        - internal
      requestBody:
        description: The request to the Lenra app
        required: true
        content:
          application/json:
            schema:
              $ref: "app-request.yml"
      responses:
        '200':
          description: The response from the Lenra app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
        '500':
          description: Unexpected app error
components:
  schemas:
    response:
      oneOf:
        - $ref: "view-response.yml"
        - $ref: "#/components/schemas/listener-response"
        - $ref: "#/components/schemas/resource-response"
    listener-response: {}
    resource-response:
      type: string
      format: binary
  