$schema: http://json-schema.org/draft-07/schema
$id: https://app.lenra.io/requests/app.yml
title: AppRequest
description: The Lenra application request
oneOf:
  - $ref: view.yml
  - $ref: listener.yml
  - $ref: resource.yml
  - $ref: manifest.yml
